-- DROP tablas
DROP TABLE USERS;
DROP TABLE AUTHORS;
DROP TABLE POEMS;
DROP TABLE REVIEWS;

-- CREATE tablas: USERS, AUTHORS, POEMS, REVIEWS
CREATE TABLE USERS(
id_user INT,
user_name VARCHAR2(20),
user_surname VARCHAR2(30),
email VARCHAR2(25),
user_password VARCHAR2(30),
CONSTRAINT PK_ID_USER PRIMARY KEY(id_user)
);

CREATE TABLE AUTHORS(
id_author INT,
author_name VARCHAR2(20),
author_surname VARCHAR2(30),
author_birthdate DATE,
author_description VARCHAR2(750),
CONSTRAINT PK_ID_AUTHOR PRIMARY KEY(id_author)
);


CREATE TABLE POEMS(
id_poem INT,
title VARCHAR2(30),
publish_date DATE,
poem_description VARCHAR2(750),
CONSTRAINT PK_ID_POEM PRIMARY KEY(id_poem),
CONSTRAINT FK_ID_AUTHOR_POEM FOREIGN KEY(id_author) REFERENCES AUTHORS
);

CREATE TABLE REVIEWS(
id_review INT,
review_rating CHAR(1),
review_content VARCHAR2(1000),
CONSTRAINT PK_ID_REVIEW PRIMARY KEY(id_review),
CONSTRAINT FK_ID_POEM_REVIEW FOREIGN KEY(id_poem) REFERENCES POEMS,
CONSTRAINT FK_ID_USER_REVIEW FOREIGN KEY(id_user) REFERENCES USERS
);